<?php

namespace App\Models;

use App\Http\Middleware\Approval;
use App\Models\BaseModel;
use App\Models\Log\ApplyLog;
use App\Models\Scope\SupplementApplyScope;
use App\Repositories\Policy\ProjectRepository;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * 申请表
 * @author lxh
 *
 */
class ApplyModel extends BaseModel
{
    // 软删除
    use SoftDeletes;
    use BelongStaff;
    use ApplyLog;

	// 表名
	protected $table = 'flo_apply';
	
	const TABLE_NAME = 'flo_apply';

	// 主键
	protected $primaryKey = 'id';
	
	// 黑名单
	protected $guarded = ['id'];

	protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::addGlobalScope(new SupplementApplyScope());
    }


    public function project()
    {
        return $this->belongsTo(ProjectModel::class, 'project_id');
    }

    public function scopeHasMold($query, $mold_id)
    {
        if (empty($mold_id)) {
            return $query;
        }

        return $query->whereHas('project', function ($q) use ($mold_id) {
            $q->withTrashed()->where('mold_id', $mold_id);
        });
    }

    public function approval()
    {
        return $this->hasOne(ApprovalModel::class, 'apply_id');
    }

    public function scopeLikeProjectMold($query, $arr)
    {
        $keyword = trim(array_get($arr, 'keyword'));
        if (empty($keyword)) {
            return $query;
        }
        return $query->where(function ($q) use ($keyword) {
            $keyword = "%$keyword%";
            $q->where('project_name','like',$keyword);
        });
    }

    public function scopeSupplement($query)
    {
        return $query->where('is_supplement',APPLY_SUPPLEMENT['yes']);
    }

    public function scopeApplyAll($query)
    {
	    return  $query->withoutGlobalScopes([ SupplementApplyScope::class]);
    }

    public function haveDepartment()
    {
        return $this->hasOne(ApprovalModel::class, 'apply_id')
            ->where(ApprovalModel::TABLE_NAME.'.type', APPROVAL_TYPE['two']);
    }

    public function mainDepartment()
    {
        return $this->hasManyThrough(StaffDepartmentModel::class,
            ApprovalModel::class,
            'apply_id',
            'id',
            'id',
            'department_id'
        )->where(ApprovalModel::TABLE_NAME.'.type', APPROVAL_TYPE['two']);
    }
}
